name: Deploy static site to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to $web
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name brusilowresumeblob \
              --destination '$web' \
              --source . \
              --overwrite
